### ISSUE TITLE
Implement AliasGroup serializer

### ISSUE THREAD

**Issue by addshore** [wmde/WikibaseDataModelSerialization#153]
This will be needed by the ResultBuilder class in Wikibase for API XML output.

**Comment by addshore** [comment]
@Benestar turns out we do needs this....

**Comment by Benestar** [comment]
How should the serialization look like then? Should it contain the language code as an array key or should it only add the language code to all aliases individually? Also do we need an AliasGroupDeserializer as well? Otherwise this should be relatively easy.

**Comment by addshore** [comment]
I only need the Serializer, although a Deserializer would likely be useful for clients.
I reckon only add the language code to the aliases individually.
This would probably mean the Deserializer should make sure all of the aliases have the same language

**Comment by JeroenDeDauw** [comment]
Keep in mind that there could be multiple serilaizers for any given object. So there is no need to make one that makes most sense for all possible use cases.
